### ISSUE TITLE
Affects layouts of other fields & header

### ISSUE THREAD

**Issue by Karuna2Karan** [vigneshr1236/PCF-365spartan-Custom-AudioAttachmentLivePreviewControl#1] opened 2019-08-21 13:05 UTC
Hey Vignesh,

Nice work! I was trying this control today in a test environment. Works but has some issues. Affecting Optionset fields and record title alignment in form header, also affecting other website controls in the form. Also the audio is uploading, but notification says failed.

![image](https://user-images.githubusercontent.com/54361970/63434187-43b4b700-c42d-11e9-894f-86ecb477ac6f.png)

**Comment by vigneshr1236** [comment] 2019-08-21 16:39
Hi Karunakaran, 
First of all, thank you for your time and efforts. I have fixed the layout and style issues and have pushed them to the repo, Can you share more inputs on the file you uploaded what was the file size?

**Comment by Karuna2Karan** [comment] 2019-08-22 09:58
File 1 size is less than 1.25 MB, MP3 format, screenshot below with notification. File 2 size 100 KB, M4a format, no notification. 
![image](https://user-images.githubusercontent.com/54361970/63505601-7964a900-c4dc-11e9-86e0-8726ab152e82.png)

**Comment by vigneshr1236** [comment] 2019-08-22 10:02
> File 1 size is less than 1.25 MB, MP3 format, screenshot below with notification. File 2 size 100 KB, M4a format, no notification.
> ![image](https://user-images.githubusercontent.com/54361970/63505601-7964a900-c4dc-11e9-86e0-8726ab152e82.png)

as of now, you can only import "mp3 format" ...  Is it possible to send the file?  so that I could have a test

**Comment by Karuna2Karan** [comment] 2019-08-22 10:09
Your email id?

**Comment by vigneshr1236** [comment] 2019-08-22 10:13
vigneshr1236@gmail.com

**Comment by vigneshr1236** [comment] 2019-08-22 10:39
![Issue Fixes](https://user-images.githubusercontent.com/35003580/63508088-dcfbd000-c4f6-11e9-9b59-e9619b52aec0.PNG)

I was not able to reproduce the issue. refer above screenshot the file got uploaded. Can you let me know for which entity form have you added the custom control...

**Comment by Karuna2Karan** [comment] 2019-08-22 11:06
I tried your control in another CRM environment, it worked without any issue.

**Comment by vigneshr1236** [comment] 2019-08-22 13:56
Okie. Will close this issue please feel free to reopen the issue if you have any troubles in the future

**Closed by vigneshr1236** 2019-08-22 13:56 UTC
